# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatRPC_pb2 as chatRPC__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/ChatService/RegisterUser',
                request_serializer=chatRPC__pb2.RegisterRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Login = channel.unary_unary(
                '/ChatService/Login',
                request_serializer=chatRPC__pb2.LoginRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Logout = channel.unary_unary(
                '/ChatService/Logout',
                request_serializer=chatRPC__pb2.LogoutRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.ChannelPost = channel.unary_unary(
                '/ChatService/ChannelPost',
                request_serializer=chatRPC__pb2.ChannelPostRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.DirectMessage = channel.unary_unary(
                '/ChatService/DirectMessage',
                request_serializer=chatRPC__pb2.DirectMessageRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Watch = channel.unary_unary(
                '/ChatService/Watch',
                request_serializer=chatRPC__pb2.WatchRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Unwatch = channel.unary_unary(
                '/ChatService/Unwatch',
                request_serializer=chatRPC__pb2.UnwatchRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Block = channel.unary_unary(
                '/ChatService/Block',
                request_serializer=chatRPC__pb2.BlockRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.Unblock = channel.unary_unary(
                '/ChatService/Unblock',
                request_serializer=chatRPC__pb2.UnblockRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.Response.FromString,
                )
        self.MessageStream = channel.unary_stream(
                '/ChatService/MessageStream',
                request_serializer=chatRPC__pb2.MessageStreamRequest.SerializeToString,
                response_deserializer=chatRPC__pb2.MessageResponse.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DirectMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unwatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Block(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unblock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MessageStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=chatRPC__pb2.RegisterRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=chatRPC__pb2.LoginRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=chatRPC__pb2.LogoutRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'ChannelPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelPost,
                    request_deserializer=chatRPC__pb2.ChannelPostRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'DirectMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectMessage,
                    request_deserializer=chatRPC__pb2.DirectMessageRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Watch': grpc.unary_unary_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=chatRPC__pb2.WatchRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Unwatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Unwatch,
                    request_deserializer=chatRPC__pb2.UnwatchRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Block': grpc.unary_unary_rpc_method_handler(
                    servicer.Block,
                    request_deserializer=chatRPC__pb2.BlockRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'Unblock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unblock,
                    request_deserializer=chatRPC__pb2.UnblockRequest.FromString,
                    response_serializer=chatRPC__pb2.Response.SerializeToString,
            ),
            'MessageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.MessageStream,
                    request_deserializer=chatRPC__pb2.MessageStreamRequest.FromString,
                    response_serializer=chatRPC__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/RegisterUser',
            chatRPC__pb2.RegisterRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Login',
            chatRPC__pb2.LoginRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Logout',
            chatRPC__pb2.LogoutRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChannelPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/ChannelPost',
            chatRPC__pb2.ChannelPostRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DirectMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/DirectMessage',
            chatRPC__pb2.DirectMessageRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Watch',
            chatRPC__pb2.WatchRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unwatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Unwatch',
            chatRPC__pb2.UnwatchRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Block(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Block',
            chatRPC__pb2.BlockRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unblock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/Unblock',
            chatRPC__pb2.UnblockRequest.SerializeToString,
            chatRPC__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MessageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/MessageStream',
            chatRPC__pb2.MessageStreamRequest.SerializeToString,
            chatRPC__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
